version: "3.9"
services:
  web:
    build: services/frontend
    ports:
      - "5000:5000"
    networks:
      - app
    depends_on: 
      - reader
      - writer
  reader:
    build: services/reader
    ports:
      - "8080:8080"
    networks:
      - app
  writer:
    build: services/writer
    ports:
      - "8081:8081"
    networks:
      - app
  redis:
    image: "redis:alpine"
    expose: 
      - 6379
    networks: 
      - app

networks:
  #backend:
  #frontend:
  app: