version: "3.9"
services:
  web:
    build: services/frontend
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
    depends_on: 
      - reader
      - writer
  reader:
    build: services/reader
    ports:
      - "8080:8080"
    networks:
      - frontend
  writer:
    build: services/writer
    ports:
      - "8081:8081"
    networks:
      - backend
  redis:
    image: "redis:alpine"
    expose: 
      - 6379

networks:
  backend:
  frontend: